### ISSUE TITLE
Error when processing large record set

### ISSUE THREAD

**Issue by maryacat** [UNC-Libraries/MARC-record-set-wrangler#1]
Received “[FATAL] failed to allocate memory” error when processing incoming file containing 33,463 records.

**Comment by kspurgin** [comment]
Working on this. Made a lot of promising progress yesterday---was able to deal with an incoming and existing set, where BOTH files had over 44,000 records. However, this involved changing the basic way the script interacts with records, and I don't have all the functions of the script re-hooked into the new way of doing things yet. 

Soon...

**Comment by kspurgin** [comment]
Hey, I have a version of this that is working. It worked on the set I have where the incoming record set and the existing record set are BOTH bigger than 44,000 records. 

Try the version of the code available from: 
Unfortunately it is SUPER SLOW. 

I thought I'd found a really good solution (developed by someone else and baked into this), but didn't understand something about how it worked internally, and when I finally tested it on the really big files, I got the same memory error. 

I reverted to the stupidest/simplest way possible to handle this.

**Comment by ldss-jm** [comment]
(The commit reference above is an error. That commit mistakenly refered to this issue, and I don't believe it's possible to delete the automatic commit references in github once they've been created.)

In any case though, it seems this issue can be closed. The memory issue was solved per the comments above. In addition, PR #16 / [v0.1.1](https://github.com/UNC-Libraries/MARC-record-set-wrangler/releases/tag/v.0.1.1) replaced the method @kspurgin describes above with a faster alternative that is still low memory usage. It also includes other changes such that overall processing speed should be improved 2x or more which may mitigate the speed concerns @kspurgin raised.
